name: "Build Ren'Py Project"
author: 'Project Alice'
description: "Build your VN project using a specified Ren'Py SDK version"
inputs:
  sdk-version:
    description: "The version of the Ren'Py SDK to use"
    required: true
    default: '7.3.2'
  project-dir:
    description: "The path to the directory where the project exists"
    required: true
    default: '.'
  output-dir:
    description: "The path to the directory where to put the index.html and other files"
    required: true
    default: './out'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sdk-version }}
    - ${{ inputs.project-dir }}
    - ${{ inputs.output-dir }}
branding:
  color: 'gray-dark'
  icon: 'archive'
